
@base_url=http://localhost:3000
@alunos_url=http://localhost:3000/alunos

## CREATE ALUNO
POST {{alunos_url}}/create
Content-Type: application/json

{
  "name": "Luan Seixas",
  "email": "luansxs25@email.com",
  "phone": "99999999999"
}

###

## GET ALL ALUNOS
GET {{alunos_url}}/